# Generated by Django 5.1.4 on 2025-01-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_producto_cantidad_alter_producto_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, unique=True),
        ),
    ]
